services:
  nextserver:
    restart: always
    build:
      context: ./nextjs-app
    ports:
      - "3000:3000"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
